development:
  storage: file
  facebook_app_id: 365401603490972
  facebook_app_key: ba9d936788748804710532f5918348bc
  facebook_return_url: http://localhost:3000/oauth/callback?provider=facebook
test:
  storage: file
  facebook_app_id: 365401603490972
  facebook_app_key: ba9d936788748804710532f5918348bc
  facebook_return_url: http://localhost:3000/oauth/callback?provider=facebook
production:
  storage: fog
  facebook_app_id: 363994853644871
  facebook_app_key: d227eb43c0609721f6d921f4b8a243ca
  facebook_return_url: http://ec2-50-17-68-61.compute-1.amazonaws.com/oauth/callback?provider=facebook
  