development:
  adapter: mysql2
  database: sp_development
  timeout: 5000
  username: root
  password: 

test:
  adapter: mysql2
  database: sp_test
  timeout: 5000
  username: root
  password: 

production:
  adapter: mysql2
  database: sp_production
  timeout: 5000
  username: root
  password: 
