development:
  adapter: mysql
  database: sp_development
  timeout: 5000
  username: root
  password: ""

test:
  adapter: mysql
  database: db/test.mysql
  timeout: 5000
  username: root
  password: ""

production:
  adapter: mysql
  database: db/production.mysql
  timeout: 5000
  username: root
  password: ""
