development:
  adapter: sqlite3
  database: db/development.sqlite3
  timeout: 5000

test:
  adapter: mysql
  database: db/test.mysql
  timeout: 5000
  username: root
  password: ""
  host: localhost

production:
  adapter: mysql
  database: db/production.mysql
  timeout: 5000
  username: root
  password: ""
  host: localhost