development:
  adapter: sqlite3
  database: db/development.mysql
  timeout: 5000
  username: root
  password: ""
  host: localhost

test:
  adapter: sqlite3
  database: db/test.mysql
  timeout: 5000
  username: root
  password: ""
  host: localhost

production:
  adapter: sqlite3
  database: db/development.mysql
  timeout: 5000
  username: root
  password: ""
  host: localhost