Location.create!(:name => "San Francisco", :city => "San Francisco")
Location.create!(:name => "San Jose", :city => "San Jose")
Location.create!(:name => "Berkeley", :city => "Berkeley")
Location.create!(:name => "Oakland", :city => "Oakland")
Location.create!(:name => "Castro Valley", :city => "Castro Valley")
Location.create!(:name => "Fremont", :city => "Fremont")
Location.create!(:name => "Lamorinda", :city => "Lamorinda")
Location.create!(:name => "San Ramon", :city => "San Ramon")
Location.create!(:name => "Walnut Creek", :city => "Walnut Creek")
Location.create!(:name => "San Mateo", :city => "San Mateo")